---
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Install Docker from repository 
      apt:
       name: docker.io
       state: present
    - name: Install pip3 package
      package:
        update_cache: yes 
        name: python3-pip
        state: latest
    - name: Install Docker SDK for Python
      pip:
       name: docker
       executable: pip3
    - name: Create Directory for projects
      file:
        path: /opt/docker
        state: directory
        mode: 0755
        owner: root
        group: root
    - name: Copy NGINX docker 
      copy:
        src: nginx
        dest: /opt/docker 
        mode: 0755
        owner: root
        group: root
    - name: Build Nginx Docker container 
      docker_image: 
        build: 
          path: /opt/docker/nginx
        name: nginx:v5
        force_source: yes
        source: build
    - name: Copy Flask docker 
      copy:
        src: flask
        dest: /opt/docker 
        mode: 0755
        owner: root
        group: root
    - name: Build Flask Docker container 
      docker_image:
        build: 
          path: /opt/docker/flask
        name: flask:v1
        source: build
    - name: Create a network
      docker_network:
        name: flask
    - name: Run Flask 1
      docker_container:
         name: flask1
         image: flask:v1 
         state: started
         exposed_ports: 5000
         networks:
           - name: flask
    - name: Run Flask 2
      docker_container:
         name: flask2
         image: flask:v1 
         state: started
         exposed_ports: 5000
         networks:
           - name: flask
    - name: Run Nginx
      docker_container:
         name: nginx
         image: nginx:v5
         state: started
         published_ports: "80:80"
         published_ports: "443:443"
         networks:
           - name: flask
    - name: Add user to docker group
      command: sudo usermod -aG docker $USER
      become: yes
      become_user: ugbd2
    - name: Selected list of containers
      docker_network:
        name: flask
        connected:
          - nginx
          - flask1
          - flask2


